# -*- coding: utf-8 -*-
"""quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vkPKjholb8G-yVhktXV_v8BXiUfZCz8

# You are given a grid as shown in the figure below. You can determine the color and number of
each square from the grid. Write python program that inputs two numbers within the grid range.
Your program will determine if the two squares entered in this grid have the same color or not
and display the appropriate message, let’s call this ROUND1. You then again ask the user to
enter two numbers and determine if the two squares have the same color then display a victory
message but this time you will have to make sure that does not repeat the numbers entered in
2the first round. If he does, give him a warning and ask to enter values again (You can give a max
of 3 warnings, on the fourth warning you will end the program). Total rounds of this guessing
game will be 5. In each round you will make sure that the numbers entered do not match with
any of the previous victory numbers.
If the user wins at least 3 rounds of this guessing game, then it's a win.

1. Input: 2 4 // are not equal =>Round1
2. Input: 9 15 //are equal =>Round2
3. Input: 9 15 //WARNING 1 and is not considered as a round3
4. Input: 16 21 //are equal =>Round3
5. Input: 16 21 //WARNING 2 and is not considered as a round4
6. Input: 9 5 //WARNING 3 and is not considered as a round4
7. Input: 29 30 // are not equal =>Round4
8. Input: 9 5 //WARNING 4 **END OF PROGRAM**
"""

grid_number=list(range(1,37))
grid_color=['green','red','blue','orange','gray','green','green','gray','orange','blue','red','green','red','blue','orange','gray','green',

'red','red','green','gray','orange','blue','red','blue','orange','gray','green','red','blue','blue','red','green','gray','orange','blue']

grid={}
for i in range(0,36):

    grid[grid_number[i]]=grid_color[i]

a=[]
a.append((5,6))
a

numbers_entered={}
warnings=3
guess=5
while warnings>0:
    while guess>0:
        inp_1=int(input())
        inp_2=int(input())

        if grid[inp_1]==grid[inp_2]:
            print('are equal')
            guess-=1

"""# q2 Write a program that displays the following menu: Welcome to Guessing games
1. Play Higher or Lower
2. Play paper - scissors - rock
3. Guess the numbers
4. Quit Enter your choice (1 - 4)
   
If the user enters 1, the program should generate two random numbers between 1 and 20 and
display the first number. It should then ask the user to enter either H or L for Higher or Lower.
The user wins if they entered H and the second number was higher than the first or when they
entered L and the second number was lower than the first.
If the user enters 2, the program should generate one random number between 1 and 3 with 1
corresponding to paper, 2 to scissors, and 3 to rock. The program should then ask the user to
enter P for paper, S for scissors, or R for rock. If the user guesses the correct corresponding
number, the program should then display who won the computer or the user. Scissors beat
paper, rock beats scissors, and paper beats rock.
Example: if the random number is 2 and the user enters the character S the program should
display, you won: Scissors beats paper. If a user enters any other character, the program should
display: you lose.


Finally, if the user enters 3, the program will generate three random numbers each between 0
and 9. The user should guess three numbers and the program should compare each of the
user's guess to the three generated random numbers and display an appropriate output based
on whether they got:
1. Any one matching
2. Two matching
3. Three matching, not in order
4. Three matching in exact order
5. No matches at all Input Validation:
Input Validation: Display an error message if the user enters a number outside the range of
through 4 when selecting an item from the menu. Do not accept characters other Than H or L
for Higher / Lower, other than P, S, and R for paper, scissors and rock , or a value outside the
range from 0 to 9 for guessing numbers. The user can play games in a repeated manner until the
user terminates the game by choice.
"""

import random
game=int(input("enter 1,2,3 or 4 "))

if game==1:
    num1=random.randint(1,20)
    num2=random.randint(1,20)


    guess=input('enter H or L')
    if guess =='H' and num2>num1:
        print('you win')
    elif guess =='l' and num2<num1:
        print('you win')
    else:
        print('You loose')

    print(f'num1 is {num1} and num2 is {num2}')
elif game==2:
    human_guess=input('Enter R for Rock, P for paper and S for Scissor')
    system_guess=random.randint(1,3)
    rps=''
    if system_guess==1:
        rps+='Paper'
    elif system_guess==2:
        rps+='Scissor'
    else:
        rps+='Rock'
    if human_guess=='R' and rps=='Scissor':
        print(f'you won Rock beats Scissor')
    elif human_guess=='P' and rps=='Rock':
        print(f'you won Paper beats Rock')
    elif human_guess=='S' and rps=='Paper':
        print(f'you won Scissors beat paper')

elif game==3:
    l=[]
    h_guess=[]

    for i in range(3):
        r_num=random.randint(0,9)
        l.append(r_num)

        my_guess=int(input('enter your number'))
        h_guess.append(my_guess)
    count=0
    for j in range(3):
        if h_guess[j] in l:
            count+=1
    print(f'human generated numbers are {h_guess} and random generated numbers are {l}.')
    print(f'matching guesses are {count}')







"""# q3: Consider an integer array, the number of elements in which is determined by the user. The elements are also taken as input from the user. Write a program to find those pairs of elements that have the maximum and minimum difference among all element pairs.use lists and tuples only"""

elements=[2,4,6,7,23,65,43]
pair_diff={}
difference=[]
for i in range(len(elements)):
    for j in range(i+1,len(elements)):


        diff=elements[i]-elements[j]
        diff=abs(diff)
        pair_diff[elements[i],elements[j]]=diff



pair_diff

maximum=max(pair_diff)
print(f'maximum distance between elements is{maximum} and their difference is {pair_diff[maximum]} ')

minimum=min(pair_diff)
print(f'maximum distance between elements is{minimum} and their difference is {pair_diff[minimum]} ')

